H = [-16 0; 0 8];
f = [-8; -16];
A = [-2 0;0 1];
conUB = [5;3];
conLB = [-%inf; -%inf];
lb = [0; 0];
ub = [%inf; %inf];
nbVar = 2;
nbCon = 2;
x0 = [1 ;1];
[xopt,fopt,exitflag,output,lambda]=quadprog(nbVar,nbCon,H,f,lb,ub,A,conLB,conUB,x0)