// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('Makelib') <> [] then
  unix_s('make -f Makelib clean');
  mdelete('Makelib');
end
// ------------------------------------------------------
if isdir('Debug') then
  rmdir('Debug','s');
end
// ------------------------------------------------------
if isdir('Release') then
  rmdir('Release','s');
end
// ------------------------------------------------------
if fileinfo('FOSSEE_Optimization_Toolbox.dll') <> [] then
  mdelete('FOSSEE_Optimization_Toolbox.dll');
end
// ------------------------------------------------------
if fileinfo('FOSSEE_Optimization_Toolbox.cpp') <> [] then
  mdelete('FOSSEE_Optimization_Toolbox.cpp');
end
// ------------------------------------------------------
if fileinfo('FOSSEE_Optimization_Toolbox.hxx') <> [] then
  mdelete('FOSSEE_Optimization_Toolbox.hxx');
end
// ------------------------------------------------------
if fileinfo('FOSSEE_Optimization_Toolbox.h') <> [] then
  mdelete('FOSSEE_Optimization_Toolbox.h');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
