// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// ----------------------------------------------------------------------------
//
libFOSSEE_Optimizat_path = get_absolute_file_path('loader.sce');
//
// ulink previous function with same name
[bOK, ilib] = c_link('libFOSSEE_Optimization_Toolbox');
if bOK then
  ulink(ilib);
end
//
link(libFOSSEE_Optimizat_path + filesep() + '-L/home/rupak19/FOT-cleanup/fot-check5/FOSSEE-Optimization-toolbox/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libSym -L/home/rupak19/FOT-cleanup/fot-check5/FOSSEE-Optimization-toolbox/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libipopt -L/home/rupak19/FOT-cleanup/fot-check5/FOSSEE-Optimization-toolbox/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libClp -L/home/rupak19/FOT-cleanup/fot-check5/FOSSEE-Optimization-toolbox/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libOsiClp -L/home/rupak19/FOT-cleanup/fot-check5/FOSSEE-Optimization-toolbox/sci_gateway/cpp//../../thirdparty/linux/lib/x64/libCoinUtils' + getdynlibext());
list_functions = [ 'linearprog';
                   'rmps';
                   'quadprog_CLP';
                   'solveqp';
                   'solveminuncp';
                   'solveminbndp';
                   'solveminconp';
                   'matintlinprog';
                   'mpsintlinprog';
                   'solveintqp';
                   'inter_fminunc';
                   'inter_fminbnd';
                   'inter_fmincon';
                   'fotversion';
];
addinter(libFOSSEE_Optimizat_path + filesep() + 'libFOSSEE_Optimization_Toolbox' + getdynlibext(), 'libFOSSEE_Optimization_Toolbox', list_functions);
// remove temp. variables on stack
clear libFOSSEE_Optimizat_path;
clear bOK;
clear ilib;
clear list_functions;
// ----------------------------------------------------------------------------
